#服务器启动端口
server:
  port: 8060
spring:
  datasource:
    #mysql url
    url: jdbc:mysql://127.0.0.1:3306/tutor?useUnicode=true&characterEncoding=utf-8
    #mysql user
    username: root
    #mysql 密码
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML5
#开启文件上传最大大小为10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#开启数据库字段名下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true